# from GitHub, overriding the name and specifying a specific tag
- src: https://github.com/CoffeeITWorks/ansible-role-nagios.git
  version: master
  name: ansible-role-nagios

- src: geerlingguy.repo-epel

- src: https://github.com/CoffeeITWorks/ansible_nagios4_server_config.git
  name: coffeeitworks.ansible_nagios4_server_config
