---
# file: task/config_plugins.yml

- name: Install Plugins dependencies
  package: name={{ item }} state=present
  with_items:
    - libnet-dns-perl  # required for check_iftraffic43a.pl
    - libnagios-plugin-perl # required for hp ilo
    - libxml-simple-perl # required for hp ilo
    - php5-sybase # required for check_mssql.php
    - update-notifier-common # Required for check_nrpe_os_update
    - snmp
    - python-pip
    - python3-pip

- name: upgrade pip
  command: "pip install {{ nagios_plugins_required_pip }}"
  changed_when: false
  tags:
    - skip-ansible-lint

- name: Install plugins from pip packages
  command: "pip2 install {{ item }}"
  changed_when: false
  with_items: "{{ nagios_plugins_pip2_packages }}"
  tags:
    - skip-ansible-lint

- name: upgrade pip3
  command: "pip3 install {{ nagios_plugins_required_pip }}"
  changed_when: false
  tags:
    - skip-ansible-lint

- name: Install plugins from pip packages
  command: "pip3 install {{ item }}"
  changed_when: false
  with_items: "{{ nagios_plugins_pip3_packages }}"
  tags:
    - skip-ansible-lint

- name: create plugins directory for plugins libs
  file: 'path={{ nagios_plugins_dir }} owner=root group=root mode=755 state=directory'

- name: Install plugins on plugins dir
  copy: 'src=plugins/ dest={{ nagios_plugins_dir }} owner=root group=root mode=755'

- name: create plugins directory for commands cfg
  file: 'path={{ nagios_config_cfg_plugins }} owner=nagios group=nagios mode=775 state=directory'

- name: configure the commands for plugins
  template:
    src: "{{ item }}"
    dest: '{{ nagios_config_cfg_plugins }}/{{ item | basename | regex_replace("\.j2","") }}'
    owner: 'nagios'
    group: 'nagios'
    mode: 0644
  with_fileglob:
    - ../templates/commands/*

  notify: Reload Nagios

- name: Configure additional plugins
  template: 
    src: '{{ item.src }}'
    dest: '{{ nagios_config_cfg_plugins }}/{{ item.dest }}'
    owner: 'nagios'
    group: 'nagios'
    mode: 0644
  with_items:
    - { src: 'check_nrpe.cfg.j2', dest: 'check_nrpe.cfg' }
    - { src: 'plugin-check_url_status.cfg.j2', dest: "plugin-check_url_status.cfg" }
  notify: Reload Nagios
