---
# file: tasks/main.yml

- import_tasks: multi_os.yml
  tags:
    - config_nagios_plugins
    - test_nagios_plugins

- import_tasks: config_plugins.yml
  tags:
    - config_nagios_plugins

- import_tasks: plugin_checkwmiplus.yml
  when: nagios_plugins_install_checkwmiplus | bool
  tags:
    - config_nagios_plugins

- import_tasks: plugin_check_netbotz.yml
  when: nagios_plugins_check_netbotz_tweaks | bool
  tags:
    - config_nagios_plugins

- import_tasks: tests.yml
  tags:
    - test_nagios_plugins
