---
# This plugin requires wmic 
# Some special steps are required and maybe not compatible with future distributions
# The compiling steps takes some time so a dedicated playbook will handle it. 
# http://www.edcint.co.nz/checkwmiplus/InstallationTerminalSession

- name: plugin_checkwmiplus | Install wmic dependencies
  package: name={{ nagios_plugin_checkwmiplus_dependencies | join(',') }} state=present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: plugin_checkwmiplus | check if wmi exists
  stat:
    path: "/bin/wmic"
  register: nagios_plugins_wmic_stat

- block: 
  
  - name: plugin_checkwmiplus | create /root/wmi-1.3.14 directory
    file: 
      path: "/root/wmi-1.3.14"
      state: directory

  - name: plugin_checkwmiplus | Uncompress wmi
    unarchive:
      src: "plugin_checkwmiplus/wmi-1.3.14.tar.gz"
      dest: "/root/wmi-1.3.14"

  - name: plugin_checkwmiplus | Compile and install wmic
    shell: 'make "CPP=gcc -E -ffreestanding"'
    become: yes
    args:
      creates: "/bin/wmic"
      chdir: "/root/wmi-1.3.14/wmi-1.3.14/"

- name: plugin_checkwmiplus | create {{ nagios_plugins_dir_opt }} directory
  file: 
    path: "{{ nagios_plugins_dir_opt }}"
    state: directory

- name: plugin_checkwmiplus | Uncompress checkwmiplus
  unarchive:
    src: "plugin_checkwmiplus/check_wmi_plus.v1.54.tar.gz"
    dest: "{{ nagios_plugins_dir_opt }}"

# TODO: Add command and services templates
