---
# This plugin requires wmic 
# Some special steps are required and maybe not compatible with future distributions
# The compiling steps takes some time so a dedicated playbook will handle it. 
# http://www.edcint.co.nz/checkwmiplus/InstallationTerminalSession

- name: plugin_checkwmiplus | Install wmic dependencies
  package: name={{ nagios_plugin_checkwmiplus_dependencies | join(',') }} state=present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: plugin_checkwmiplus | check if wmi exists
  stat:
    path: "/bin/wmic"
  register: nagios_plugins_wmic_stat

- block: 
  
  - name: plugin_checkwmiplus | create /root/wmi-1.3.14 directory
    file: 
      path: "/root/wmi-1.3.14"
      state: directory

  - name: plugin_checkwmiplus | Uncompress wmi
    unarchive:
      src: "plugin_checkwmiplus/wmi-1.3.14.tar.gz"
      dest: "/root/wmi-1.3.14"

  - name: plugin_checkwmiplus | Compile and install wmic
    shell: 'make "CPP=gcc -E -ffreestanding"'
    become: yes
    args:
      creates: "/bin/wmic"
      chdir: "/root/wmi-1.3.14/wmi-1.3.14/"

- name: plugin_checkwmiplus | create {{ nagios_plugins_dir_opt }} directory
  file: 
    path: "{{ nagios_plugins_dir_opt }}"
    state: directory

- name: plugin_checkwmiplus | Uncompress checkwmiplus
  unarchive:
    src: "plugin_checkwmiplus/check_wmi_plus.v1.54.tar.gz"
    dest: "{{ nagios_plugins_dir_opt }}"

- name: plugin_checkwmiplus | test plugin checkwmiplus
  shell: perl {{ nagios_plugins_dir_opt }}/check_wmi_plus.pl --version
  changed_when: False

# TODO: Add command and services templates

- name: plugin_checkwmiplus | configure the commands for checkwmi_plugins
  template:
    src: "{{ item.src }}"
    dest: "{{ nagios_config_cfg_plugins }}/{{ item.dest }}"
    owner: 'nagios'
    group: 'nagios'
    mode: 0644
  with_items:
    - { src: 'plugin_checkwmiplus/plugin_checkwmiplus.cfg.j2', dest: 'plugin_checkwmiplus.cfg' }
  notify: Reload Nagios

# TODO: Add
# - The following $USER$ Macro are required and are defined in the Nagios config file normally called resource.cfg
# - $USER6$ set to the installation directory for check_wmi_plus.pl.
# - $USER8$ and $USER9$ set to the username and password used for accessing WMI on Windows.
# to: {{ nagios_etc }}/resource.cfg

- name:  plugin_checkwmiplus | lineinfile - configure resource.cfg $USER6$ $USER8$ $USER9$
  lineinfile: dest="{{ nagios_etc }}/resource.cfg" regexp='{{ item.src }}' line="{{ item.value }}"
  with_items:
  - src: "^$USER6$="
    value: "$USER6$={{ nagios_plugins_dir_opt }}"
  - src: "^$USER8$="
    value: "$USER8$={{ nagios_plugins_USER8_wmi_username }}"    
  - src: "^$USER9$="
    value: "$USER9$={{ nagios_plugins_USER9_wmi_password }}"    
  notify: Reload Nagios
  tags:
    - nagios_server_main_config
