# file: nagios-server/handlers/main.yml

- name: Reload Nagios
  service:
    name: "{{ nagios_service }}"
    state: reloaded
  notify: Restart Nagios

- name: Restart Nagios
  service:
    name: "{{ nagios_service }}"
    state: restarted
