---
- name: Converge
  hosts: all
  vars:
    nagios_plugins_install_checkwmiplus: True
  roles:
    - role: ansible-role-nagios
    - role: coffeeitworks.ansible_nagios4_server_config
    - role: ansible_nagios4_server_plugins
